version: '3.2'

services:
  occloxium:
    container_name: occloxium.com
    image: registry.git.rwth-aachen.de/occloxium-webdev/occloxium.com
    ports:
      - 7000:80
    restart: always

networks:
  default:
    external:
      name: occloxium
